name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android 64-bit
            os: ubuntu-latest
            target: Android64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          
