name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: geode-sdk/build-geode-mod@main
        with:
          target-win: true
          target-android-64: true
          
