name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Mod
    uses: geode-sdk/build-geode-mod/.github/workflows/build.yml@main
    with:
      build-win: true
      build-android-64: true
      build-android-32: false
      build-mac: false
      
